/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface ICompatibilityConfidence {
    function owner() external view returns (address);

    function registry() external view returns (address);

    function pendingOwner() external view returns (address);

    function transferOwnership(address new_owner) external;

    function acceptOwnership() external;

    function setRegistry(address new_registry) external;

    function setPrior(bytes32 release_digest, uint8 profile_index, uint32 passes, uint32 failures, bytes32 evidence_digest) external;

    function record(bytes32 release_digest, uint8 profile_index, bool passed, uint16 weight_bps) external;

    function confidence(bytes32 release_digest, uint8 profile_index) external view returns (uint16, uint64);

    function stats(bytes32 release_digest, uint8 profile_index) external view returns (uint128, uint128, uint64, uint32, uint32);

    error NotOwner(address);

    error NotRegistry(address);

    error NotPendingOwner(address);

    error ZeroOwner();

    error WeightTooLarge(uint16);
}
