import { readFileSync } from "node:fs";

import type { Outcome, Prior, Stats } from "../src/index.js";

/** contracts/stylus/lemma-confidence/vectors.json, generated by the Rust crate. */
export const VECTORS_PATH = new URL("../../../contracts/stylus/lemma-confidence/vectors.json", import.meta.url);

interface JsonStats {
  passWad: string;
  failWad: string;
  last: string;
}

interface Vectors {
  schema: string;
  constants: { wad: string; halfLifeSeconds: string; maxWeightBps: number; zWad: string; z2Wad: string; fractionBits: number; decayTable: string[] };
  decay: { name: string; valueWad: string; dt: string; expected: string }[];
  record: { name: string; stats: JsonStats; passed: boolean; weightBps: number; now: string; expected: JsonStats }[];
  confidence: { name: string; prior: Prior; stats: JsonStats; now: string; expected: { confidenceBps: number; effectiveNMilli: string } }[];
  fold: {
    name: string;
    prior: Prior;
    outcomes: { passed: boolean; weightBps: number; at: string }[];
    now: string;
    expected: { stats: JsonStats; confidenceBps: number; effectiveNMilli: string };
  }[];
}

export const vectors = JSON.parse(readFileSync(VECTORS_PATH, "utf8")) as Vectors;

export const stats = (s: JsonStats): Stats => ({ passWad: BigInt(s.passWad), failWad: BigInt(s.failWad), last: BigInt(s.last) });
export const outcome = (o: { passed: boolean; weightBps: number; at: string }): Outcome => ({ passed: o.passed, weightBps: o.weightBps, at: BigInt(o.at) });
